print('Welcome to the tip calculator.')
totalBill = float(input('What is the total bill?\n$'))
tipPercentage = int(input('What percentage tip would you like to give?\n'))
peopleSplit = int(input('How many people to split the bill?\n'))
pricePerPerson = round((totalBill + totalBill*(tipPercentage/100)) / peopleSplit, 2)
print(f'Each person should pay: {pricePerPerson}')